service: account
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2

functions:
  accountLogin:
    handler: src/accountLogin.accountLogin
    events:
      - httpApi:
          path: /account/login
          method: post
